name: webpack-umd-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
permissions:
    contents: write

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: curl node-v18.12.1-win-x64.zip
        shell: cmd
        run: |
          curl https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip -L --output node-v18.12.1-win-x64.zip &&^
          7z.exe x node-v18.12.1-win-x64.zip
        
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            set PATH=^
            ${{ github.workspace }}\node-v18.12.1-win-x64;
            npm install &&^
            npm run-script build

      - shell: cmd
        run: cd dist && ren main.js cpk-automated-${{ github.ref_name }}.js
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/cpk-automated-${{ github.ref_name }}.js"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
